### ISSUE TITLE
Encountering `InvalidArchiveError`

### ISSUE THREAD

**Issue by JSLJ23** [freecurve/interx_arrow-nn_suite#2]
I was trying to install the `tar.bz2` package both with `mamba install ./simulation-0.58-0.tar.bz2` and `conda install ./simulation-0.58-0.tar.bz2` via git cloning the repository and downloading it as a zip archive but both seem to produce this error:
```
Downloading and Extracting Packages
                                                                                                    

InvalidArchiveError('Error with archive /home/user/mambaforge/pkgs/simulation-0.58-0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: Invalid data stream')
```

Any idea how I could go about resolving it?

**Comment by freecurve** [comment]
Install Git LFS before cloning the repo, the archive is on LFS. 

I will add this step into README, thank you!
